version: '3.7'
services:
  app:
    image: ${DOCKER_IMAGE}
    ports:
      - ${PORT}:3000
    command: ["dev"]
    volumes:
      - ./app:/app
      - node_modules:/app/node_modules

volumes:
  node_modules:
