version: '3.7'
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/log/nginx:/var/log/nginx
    networks:
       - haproxy-controller_haproxy-controller

  app:
    image: ${DOCKER_IMAGE}
    networks:
       - haproxy-controller_haproxy-controller

networks:
   haproxy-controller_haproxy-controller:
      external: true
